#!/usr/bin/env php
<?php
/**
 * This application is tool for worked on Opencart and ocStore
 *
 * @author Mykhailo Yatzyshyn
 * @copyrait 2018
 */

// Autoload
$librarys = glob(__DIR__ . '/app/Library/*.php');
foreach ($librarys as $lib) {
    include_once $lib;
}

include_once __DIR__ . '/app/Console.php';
$console = new \Console\Console;
$console->initApp($argv);
try {
    $console->callCommand();
} catch (Exception $e) {
    $console->message->addMessage(
            $e->getMessage(),'light_red'
    );
}